### ISSUE TITLE
Implementation von File-Lazy-Loader

### ISSUE THREAD

**Issue by LBeckX** [1601com/File-lazy-loader#1]
## Ziel (SMART)
*Wir brauchen eine neue ordentliche Erweiterung, die SeoSee ersetzt. Diese muss folgendes können:*

## Teilprojekt
* [x] Einrichtung von File-Lazy-Loader
* [x] Kopieren der Struktur wo sinnvoll
* [x] Löschen der alten Erweiterung: `bundles/agentur1601com/SeoSee`

___
* Schritt 1 - Implementation von Style-Loader
  * Es müssen die Standardloader von Contao für Styles (less, scss, sass) genutzt werden
  * Änderungen an SCSS-Dateien, die importiert werden, müssen getrackt werden und die Src-Datei neu komprimiert werden (Beispiel für das Tracken `/kunden/sip-meeting.org/contao49/src/App/Assets/CheckModified.php`)
  * [x] Styles müssen normal geladen werden können + Komprimierung (Contao-Style-Loader nutzen)
  * [x] Styles müssen Preload geladen werden können
  * [x] Styles müssen Preload Push geladen werden können
  * [x] Styles müssen Lazy über JS mit noscript-Fallback geladen werden können
  * [x] Im Menü muss ein Eintrag mit einer kurzen Beschreibung existieren (Agentur Core-Bundle)

## Ressourcen & Projektinformationen
* **Projektleitung:** @LBeckX 
* **Q-Aufgabe: Contao-Erweiterung File-Lazy-Loader (1601g-1-21-3290)** 
* **Stundenfreigabe:** 12 h
* **Deadline:** 21.01.2021

## Status
* [x] Briefing (Vorbesprechung)
* [x] Aufwandseinschätzung abgegeben
* [x] Angeboten *(PL)*
* [x] Beauftragt *(PL)*
* [x] Projektiert / Aufgabe angelegt *(PL)*
* [x] Ready for Development / KickOff *(PL -> MA)*
* [x] Umsetzung begonnen *(MA)*
* [x] Umsetzung abgeschlossen *(MA)*
* [x] [Qualitätssicherung](https://github.com/1601com/Agenturprozess/wiki/Prozesse:-DigitalMedia:-2AC-4AC) *(PL + MA)*
* [x] Freigabe durch ProductOwner *(PL)*
* [ ] Fakturiert *(PL)*
* [ ] [Debriefing](https://github.com/1601com/Agenturprozess/wiki/Prozesse:-Debriefing-Vorlage) *(PL)*

**Comment by ff1601com** [comment]
### Aktualisieren der Erweiterung
- Aufteilung in EventListener, Services, Dca, .. etc
- Anpassen der Konfigurations-Dateien
- Einrichten von Autowiring
- Anpassen der composer.json

**Comment by ff1601com** [comment]
### AbstractLoader als Basis des Bundles
Der AbstractLoader in `/EventListener/Loader/` soll als Basis des Bundles dienen, da hier beide Anwendungsfälle (JS/Style) abgedeckt werden können.

##

#### Informationen für @LBeckX 
##### Style
- StyleLoader.php ist geupdatet und zeigt nun ein Beispiel, wie es von @FlorianScheyer angedacht war
- Ordner können geladen werden und die zugehörigen Style Dateien werden dann im Backend angezeigt
  - [ ] Fix: Bei der Ordnerauswahl kommt es durch ein `unserialize `zu einem Warning im Entwicklermodus
- Beim StyleLoader konnte ich bisher nur die Implementierung im Backend testen

##### JS
- Der JS-Loader ist noch auf dem geupdateten Stand des SeoSee-Bundles
- Hier müssen die Anpassungen und Struktur aus dem StyleLoader übernommen werden
- Außerdem muss er auch die AbstractLoader-Klasse extenden

##

#### Zusätzliche Informationen
- Es liegt ein Backend von @FlorianScheyer Stand hier: `/bundles/file-lazy-loader_210122_bak_ff`

##

Bei Fragen kannst du mir natürlich auch während der Berufschule schreiben.

**Comment by ps1601com** [comment]
@LBeckX wie geht's hier weiter, es warten ein paar Projekte darauf.

**Comment by LBeckX** [comment]
Ist durch

**Comment by FlorianScheyer** [comment]
Ich kümmere mich um die Integration in Samion
